name: Security Scanning

on:
    schedule:
        - cron: "0 2 * * *" # Run daily at 2 AM UTC
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    container-scanning:
        name: Container Image Security Scan
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: [vote, result, worker]
        permissions:
            contents: read
            security-events: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build image for scanning
              run: |
                  docker build -t ${{ matrix.service }}:scan ./${{ matrix.service }}

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: ${{ matrix.service }}:scan
                  format: "sarif"
                  output: "trivy-results-${{ matrix.service }}.sarif"

            - name: Upload Trivy results to GitHub Security
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: "trivy-results-${{ matrix.service }}.sarif"

            - name: Run Trivy (Table format)
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: ${{ matrix.service }}:scan
                  format: "table"
                  exit-code: "1"
                  severity: "CRITICAL,HIGH"

    dependency-scanning:
        name: Dependency Security Scan
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: [vote, result, worker]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/docker@master
              continue-on-error: true
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  image: ${{ matrix.service }}:latest
                  args: --severity-threshold=high

    code-scanning:
        name: Code Security Analysis
        runs-on: ubuntu-latest
        permissions:
            security-events: write
            actions: read
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                  languages: javascript, python

            - name: Autobuild
              uses: github/codeql-action/autobuild@v3

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3

    secrets-scanning:
        name: Secrets Detection
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Run Gitleaks
              uses: gitleaks/gitleaks-action@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    k8s-security:
        name: Kubernetes Security Scan
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Kubesec
              uses: controlplaneio/kubesec-action@master
              with:
                  input: k8s/manifests/*.yaml

            - name: Scan with Datree
              uses: datreeio/action-datree@main
              with:
                  path: "k8s/manifests/*.yaml"
                  cliArguments: "--only-k8s-files --ignore-missing-schemas"
              continue-on-error: true

    summary:
        name: Security Summary
        runs-on: ubuntu-latest
        needs:
            [container-scanning, code-scanning, secrets-scanning, k8s-security]
        if: always()

        steps:
            - name: Create security summary
              run: |
                  echo "## Security Scan Summary" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "- Container Scanning: ${{ needs.container-scanning.result }}" >> $GITHUB_STEP_SUMMARY
                  echo "- Code Scanning: ${{ needs.code-scanning.result }}" >> $GITHUB_STEP_SUMMARY
                  echo "- Secrets Detection: ${{ needs.secrets-scanning.result }}" >> $GITHUB_STEP_SUMMARY
                  echo "- K8s Security: ${{ needs.k8s-security.result }}" >> $GITHUB_STEP_SUMMARY
